name: Scribbles
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#0e121d'
    - '#503f38'
    - '#9ba2aa'
    - '#e8c69f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
