name: Scribbles
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#678fa4'
    - '#040404'
    - '#243e4e'
    - '#e1e1e1'
    - '#805731'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
