name: Scribbles
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c3c3c'
    - '#fbfbfb'
    - '#92a7c4'
    - '#7689a5'
    - '#c0d3eb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
