name: Scribbles
favicon: null
layout_spectrum: 0.00685
typography_spectrum: 0.43326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#f2f6f9'
    - '#d7d6db'
    - '#7f685d'
    - '#bdaba7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
