typography_spectrum: 0.43326
color:
  brandColors:
    - '#333333'
    - '#f2f6f9'
    - '#d7d6db'
    - '#7f685d'
    - '#bdaba7'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00685
analytics:
  google: null
  facebook: null
  twitter: null
name: Scribbles
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Han Sijmons
purpose: []
